### ISSUE TITLE
View Collapses on Working Set ID Change

### ISSUE THREAD

**Issue by Lenzinga** [Open-Agriculture/AgIsoTerminalDesigner#10]
When the working set ID is changed, the view on the top-left collapses unexpectedly. This disrupts the workflow and requires users to manually expand the view again.

**Steps to Reproduce:**
- Open an iop with a Working set and objects below it
- Expand the Working Set to see objects below it
- Change the working set ID, either per dragging the mouse or entering a number
- Observe that the view collapses.

**Expected Behavior:**
The view should remain in its expanded state when the working set ID is changed.

Browser: Edge
OS: Windows

**Comment by GwnDaan** [comment]
Blocked by #13
